version: '3'
services:
  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - postgres
    env_file:
      - ./config.monitoring
  postgres:
    build: .
    image: anastasia/postgresql-timescaledb-pipelinedb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432